### ISSUE TITLE
Condition with just attribute_not_exists throws Dynamo error

### ISSUE THREAD

**Issue by DanielCender** [tuplo/dynoexpr#1]
### Issue
---
When putItem or updateItem operation is run with the condition specified below, Dynamo generates an error: `"message": "ExpressionAttributeValues must not be empty"`

```js
const params = dynoexpr({
    Item: {
      pk,
      sk,
      attr1,
      attr2
    },
    // Failing condition:
    Condition: {
      pk: 'attribute_not_exists',
    },
    // Correct conditional string:
    // ConditionExpression: 'attribute_not_exists(sk)',
  })
```

I believe special checks should be added to the condition helper so only `ExpressionAttributeNames` is generated when the only conditions specified are either `attribute_not_exists` or `attribute_exists`.

#### Current Output:
```js
"ConditionExpression": "(attribute_not_exists(#ne9e9))",
  "ExpressionAttributeNames": {
    "#ne9e9": "sk"
  },
  "ExpressionAttributeValues": {}
```
#### Expected Output:
```js
"ConditionExpression": "(attribute_not_exists(#ne9e9))",
  "ExpressionAttributeNames": {
    "#ne9e9": "sk"
  }
```

**Comment by ruicosta042** [comment]
Thanks Daniel
