### ISSUE TITLE
Type error on params being passed into `docClient.update`

### ISSUE THREAD

**Issue by richardtapendium** [tuplo/dynoexpr#16]
Hi,

This is my code snippet:

```
export const updateOrderViewerItem = async ({ order }: Args) => {
  const docClient = new AWS.DynamoDB.DocumentClient();
  const { ORDER_VIEW_TABLE_NAME } = process.env;
  const dynamoOrder = mapOrderToDynamoFields(order);
  const { OrderUUID, CustomerId, ...restOrder } = dynamoOrder;

  // get original item, or do we use a patch?
  const params = dynoexpr({
    TableName: ORDER_VIEW_TABLE_NAME,
    Key: { OrderUUID, CustomerId },
    Update: {
      ...restOrder
    }
  });

  Log.debug('Params', params);

  await docClient.update(params).promise();

  return order;
};
```

I seem to be getting the following error:

![image](https://user-images.githubusercontent.com/65693691/94504579-76de9200-024c-11eb-95a4-b8a679f3375c.png)

Normally I would just cast the type like so:

```
const params = dynoexpr({
    TableName: ORDER_VIEW_TABLE_NAME,
    Key: { OrderUUID, CustomerId },
    Update: {
      ...restOrder
    }
  }) as UpdateItemInput;
```

However that produces this error:

![image](https://user-images.githubusercontent.com/65693691/94504864-24ea3c00-024d-11eb-8b10-11905ce329bb.png)

I suspect `TableName` and `Key` being missing from the `DynoexprOutput` is the issue, as when I apply a type like so:

```
type PatchedDynoexprOutput = DynoexprOutput & { TableName: string; Key: any }

const params = dynoexpr({
  // truncated
  }) as PatchedDynoexprOutput;
```

Everything works fine. Happy to do a PR for this if this is a suitable solution.

**Comment by ruicosta042** [comment]
hi @richardtapendium thanks for the bug report and offer to help. I've tried solving this issue with a generic type. You can check it out at #17 . Please tell if this solves your use case. Cheers

**Comment by richardtapendium** [comment]
Thanks @ruicosta042 for the quick response, that looks like it should solve our problem!
