### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by richardtapendium** [tuplo/dynoexpr#18]
Hi,

Thanks for the awesome library. 

I'm trying to update an item with a list of objects like so:

```
const params = dynoexpr({
    TableName: TABLE_NAME,
    Key: { uuid },
    Update: {
      RoomNumber: room.roomNumber,
      Bro: [{mate: 'bro'}],
    },
  });
```

However, since the array gets converted to a `Set`, and not a `List`, it doesn't support `Map`'s inside of it. What is the recommended way for handling this situation?

**Comment by ruicosta042** [comment]
thanks @richardtapendium, that was a bug - PR #19 fixes it. Please let me know if you have any other issues. Cheers
