### ISSUE TITLE
UpdateAdd attributes don't match

### ISSUE THREAD

**Issue by cranberyxl** [tuplo/dynoexpr#24]
The `ExpressionAttributeValues` in the README match for `UpdateAdd`, but not in the test or the code: https://github.com/tuplo/dynoexpr/blob/main/src/expressions/update.test.ts#L218-L240

See `:v0a80` not matching `:v686c`

```js
const params = dynoexpr({
  UpdateAdd: {
    Color: ['Orange', 'Purple'],
  },
});
/*
  {
    UpdateExpression: 'ADD #n7295 :v0a80',
    ExpressionAttributeNames: { '#n7295': 'Color' },
    ExpressionAttributeValues: {
      ':v686c': Set { wrapperName: 'Set', values: [Array], type: 'String' }
    }
  }
*/
```

I'll dig into the code, but I'm wondering if I'm missing something with how I'm using it.

**Comment by cranberyxl** [comment]
Found the problem, the value is being converted to a set before the ket is being generated. I'll have a fix shortly

**Comment by ruicosta042** [comment]
thanks @cranberyxl merged
