### ISSUE TITLE
Question: Support for multiple values for the same attribute

### ISSUE THREAD

**Issue by belezebu** [tuplo/dynoexpr#26]
Hey everyone!

Currently there is support for having multiple conditions for the same attribute ?

I'm trying to build this condition:

```
{
   Condition: 'attribute_not_exists(key) OR key = :value'
}
```

Thank you

**Comment by ruicosta042** [comment]
Hi @belezebu there's a PR #27 for this, it allows this:

```
{
  Condition: {
    key: ['attribute_not_exists', 'value']
  }
}
```

**Comment by belezebu** [comment]
Thank you @ruicosta042 :)

**Comment by ruicosta042** [comment]
@belezebu your expression would translate to this actually:
```
{
  Condition: {
    key: ['attribute_not_exists', 'value']
  },
  ConditionLogicalOperator: 'OR'
}
```
