### ISSUE TITLE
Edge Case: Update attribute operator parsing issues

### ISSUE THREAD

**Issue by DanielCender** [tuplo/dynoexpr#3]
### Issue
---
- In using this package, we have run into an issue where my update parameters are parsed out as math expressions, when they need to be interpreted as literal strings.

### Example Case

In this case, the contract field should be interpreted as a literal string. Instead, it gets cut up into an equation and the resulting parameters result in an error (shown below).
```js
const params = dynoexpr({
  Key: {
    pk: `project#${id}`,
    sk: `project#${id}#detail`,
  },
  Update: {
    contract: '10-20-001', // <- This gets spliced up as a math expression
    updated: Date.now(),
  },
  ConditionExpression: 'attribute_exists(sk)',
})
```
![Screen Shot 2020-05-29 at 11 15 34 AM](https://user-images.githubusercontent.com/29311755/83281566-e3159000-a19d-11ea-839f-482a5af31cc0.png)
The params that caused the error:
![Screen Shot 2020-05-29 at 11 16 30 AM](https://user-images.githubusercontent.com/29311755/83281587-ec066180-a19d-11ea-8709-c95bd08150e7.png)

### Fix

- Suggestion is to add a flag to the update parameters which can tell `getExpressionAttributes` whether or not to parse operational values or interpret the attribute value literally, right [here](https://github.com/CCG-Dev/dynoexpr/blob/dc022d4704b0772570e8a126d190e6274a2a7513/src/update.ts#L34).

**Comment by ruicosta042** [comment]
I put up a PR to fix this issue, I chose to get better at detecting math operators, I'm trying to avoid introducing flags. Please take a look, tell us what you think about it #4

**Comment by DanielCender** [comment]
@ruicosta042 I checked it out, looks like a great fix! Thanks for the fast response 👍
