### ISSUE TITLE
New build style in 1.24 and 1.25 causing new errors

### ISSUE THREAD

**Issue by cranberyxl** [tuplo/dynoexpr#30]
When upgrading, we saw this:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/.../node_modules/@tuplo/dynoexpr/dist/index.js
require() of ES modules is not supported.
require() of /Users/.../node_modules/@tuplo/dynoexpr/dist/index.js from /Users/.../src/clients/dynamo.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/.../node_modules/@tuplo/dynoexpr/package.json.
```

**Comment by ruicosta042** [comment]
hi, 1.26 reverts back to having CommonJS as the default format, so everything should work as before.

btw, I'm cutting a new version (v2) where ESM will be the default format, and CommonJS a deep import

**Comment by ruicosta042** [comment]
actually if you're using node >= 13.10.0, you can use v2.4.0 and keep the code as is:

```
const dynoexpr = require('@tuplo/dynoexpr');
```

more details here: https://github.com/tuplo/dynoexpr#install

**Comment by cranberyxl** [comment]
While this approach now works for command-line node, it doesn't work for jest. What are the advantages of making this breaking change?

**Comment by ruicosta042** [comment]
you can still use v1.26.0, it works as before.

Having ESM export as default is where the ecosystem is going, other library makers have made that jump (ex: sindresorhus).

To make it work with Jest you need to add a flag to node `--experimental-vm-modules` while Jest itself doesn't upgrade to ESM. You can see how it's working here: https://github.com/tuplo/dynoexpr/blob/main/e2e/package.json#L11

**Comment by ruicosta042** [comment]
for v1, it stays the same.

for v2, while Jest doesn't support ESM natively, you'll need to import the CJS version explicitly
```
const dynoexpr = require('@tuplo/dynoexpr/cjs');
```

I've added a Jest/CommonJS e2e test here https://github.com/tuplo/dynoexpr/blob/main/e2e/main-cjs.test.js

**Comment by cranberyxl** [comment]
I would have to change every place I import `dynoexpr` to use the deep import so jest works. I don't understand the value.

**Comment by ruicosta042** [comment]
I understand your frustration, but v1.x has no changes and will keep being supported until all kinks with ESM are fixed.

**Comment by ruicosta042** [comment]
@cranberyxl you can use a configuration on Jest to keep using `require('@tuplo/dynoexpr')` with v2.x (while Jest doesn't support ESM)

```json
 {
   "jest": {
     "moduleNameMapper": {
       "dynoexpr$": "<rootDir>node_modules/@tuplo/dynoexpr/cjs"
    }
  }
}
```
