### ISSUE TITLE
High Severity Security Issue In aws-sdk Dependency

### ISSUE THREAD

**Issue by svozza** [tuplo/dynoexpr#36]
As per the title, the version of the `aws-sdk` used in the library is very old and there's been a reported vulnerability here:

https://github.com/advisories/GHSA-rrc9-gqf8-8rwg

**Comment by ruicsh** [comment]
hi, 2.9.0 has upgraded aws-sdk to latest 2.1031.0, cheers

**Comment by svozza** [comment]
That was quick! Good stuff.
