### ISSUE TITLE
logical operator "OR" doesn't work

### ISSUE THREAD

**Issue by mkarsene** [tuplo/dynoexpr#37]
Here's the example code

`var dynoexpr = require("@tuplo/dynoexpr")

const itemParams = dynoexpr({
      Update: {
modified: new Date().toJSON(),
GSI1_PK:"OPEN",
GSI2_PK:"REQUEST#STATUS#open#DATE#2022-03-01t13:58:09.242z"
},
      Condition: {
        status: ["IN_PROGRESS", "OPEN"],
      },
      logicalOperator: 'OR',
    })
    console.log(
      itemParams,
    )`

and here's the result

`{
  logicalOperator: 'OR',
  ConditionExpression: '(#n6258 = :vccc9) AND (#n6258 = :vf5c3)',
  ExpressionAttributeNames: {
    '#n6258': 'status',
    '#n98d5': 'modified',
    '#n2461': 'GSI1_PK',
    '#nb7bd': 'GSI2_SK'
  },
  ExpressionAttributeValues: {
    ':vccc9': 'IN_PROGRESS',
    ':vf5c3': 'OPEN',
    ':vbe1d': '2022-03-01T19:54:02.925Z',
    ':v5c8a': 'REQUEST#STATUS#open#DATE#2022-03-01t13:58:09.242z'
  },
  UpdateExpression: 'SET #n98d5 = :vbe1d, #n2461 = :vf5c3, #n6258 = :vf5c3, #nb7bd = :v5c8a'
}`

condition expression should be OR not AND according to documentation

**Comment by mkarsene** [comment]
temporary fix by doing `itemParams.ConditionExpression = itemParams.ConditionExpression.replace(
      'AND',
      'OR',
    )`

**Comment by ruicsh** [comment]
Hi, thanks for pointing this error on the docs.
You should use `ConditionLogicalOperator` instead of `logicalOperator`, like this:

```typescript
dynoexpr({
  Update: {
    modified: new Date().toJSON(),
    GSI1_PK: 'OPEN',
    GSI2_PK: 'REQUEST#STATUS#open#DATE#2022-03-01T13:58:09.242z',
  },
  Condition: {
    status: ['IN_PROGRESS', 'OPEN'],
  },
  ConditionLogicalOperator: 'OR',
});
 ```
