### ISSUE TITLE
dynoexpr doesn't support if_not_exists

### ISSUE THREAD

**Issue by dawidk92** [tuplo/dynoexpr#39]
## Current behavior

Right now the output of the code below looks like this:

```js
import dynoexpr from '@tuplo/dynoexpr';

const params = dynoexpr({
  Update: { number: 'if_not_exists(420)' },
});

/*
{
  params: {
    UpdateExpression: 'SET #n15df = :vc32f',
    ExpressionAttributeNames: { '#n15df': 'number' },
    ExpressionAttributeValues: { ':vc32f': 'if_not_exists(420)' }
  }
}
*/
```

## Expected behavior

With the support of `if_not_exists` the output should look like this:

```js
/*
{
  params: {
    UpdateExpression: 'SET #n15df = if_not_exists(#n15df, :vc32f)',
    ExpressionAttributeNames: { '#n15df': 'number' },
    ExpressionAttributeValues: { ':vc32f': '420' }
  }
}
*/
```

## Docs
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.PreventingAttributeOverwrites

**Comment by ruicsh** [comment]
Hi dawidk92, thanks for the report. We added `if_not_exists` support on the latest release just now, `2.11.0`

**Comment by dawidk92** [comment]
Wow @ruicsh that was super fast and it works like a charm! 🎉
