### ISSUE TITLE
parseInValue: Regex attempts to parse invalid Condition Expressions in Filter strings

### ISSUE THREAD

**Issue by DanielCender** [tuplo/dynoexpr#5]
## Desc
---
- Experienced some issues when a params.Filter is defined as `Inspector` or any string that starts with `In`.
- The `parseInValue` helper is triggered by the Regexp [here](https://github.com/tuplo/dynoexpr/blob/6c1bc8ac2330d410db32f5066a82dbfb97f118d8/src/condition-helpers.ts#L75), but it is not parsed by the tighter Regexp in the actual `parseInValue` helper: `/^in\s*\(([^)]+)/i`. This throws an error (will try to nab a screenshot of it).

**Main Question**: Is there a reason that different Regex expressions are used in these different places? It would seem like the Regex used in `parseInValue` should be used on ln. 75 (and so on for all the other helpers), otherwise regular strings will be unintentionally parsed as condition expressions.

**Comment by ruicosta042** [comment]
there's a PR up to fix this issue, PR #6 - it handles this situation and the other possible ambiguous values. Tell us what you think, cheers!
