### ISSUE TITLE
Support for batch and transact expressions?

### ISSUE THREAD

**Issue by mikestopcontinues** [tuplo/dynoexpr#7]
I really like that with basic methods, it's possible to simply pass the entire request object in. This doesn't work for batch and transaction requests, since the expressions are all nested. Is it on the roadmap to support parsing the complete expressions for batch and transaction requests?

**Comment by ruicosta042** [comment]
There's a PR #8 open now, tell us if this is what you had in mind, cheers.

**Comment by mikestopcontinues** [comment]
Oh, yes exactly! Cheers!
