### ISSUE TITLE
FR: Support multiple update actions

### ISSUE THREAD

**Issue by mikestopcontinues** [tuplo/dynoexpr#9]
[UpdateExpression](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html) supports using all four actions across multiple properties simultaneously. It would be great to be able to generate those properties easily. Perhaps using `{UpdateSet, UpdateRemove, UpdateAdd, UpdateDelete}`? What do you think?

**Comment by ruicosta042** [comment]
hi @mikestopcontinues, thanks for your suggestion. I have it implemented on PR #10 but don't have access to a DDB right now so I can't test one assumption, maybe you can help? 

The docs are not very explicit about how the `UpdateExpression` should be constructed. I'm guessing it's just a simple concatenation of the different clauses starting with keywords SET/ADD/REMOVE/DELETE:

Given this input to `dynoexpr`:
```
{
  UpdateSet: { ufoo: 'ufoo - 2' },
  UpdateRemove: { rfoo: 'rbar' },
  UpdateAdd: { afoo: 'abar' },
  UpdateDelete: { dfoo: 'dbar' },
}
```

It would produce:
```
{
  UpdateExpression:
    'SET #nff12 = #nff12 - :v862c REMOVE #nff12, #n978b ADD #nb01c :ve948 DELETE #nd358 :v45cc',
  ExpressionAttributeNames: {
    '#n978b': 'rfoo',
    '#nb01c': 'afoo',
    '#nd358': 'dfoo',
    '#nff12': 'ufoo',
  },
  ExpressionAttributeValues: {
    ':v45cc': 'dbar',
    ':ve948': 'abar',
  },
}
```

Is this your understanding, too? Cheers

**Comment by mikestopcontinues** [comment]
That was my understanding as well. I'll test it today. Thanks for your help!

**Comment by mikestopcontinues** [comment]
Things are looking good! `SET`, `REMOVE`, and `ADD` (add for numbers) all work concatenated with a space. I was also able to get `ADD` (for sets) and `DELETE` working too, using `docClient.createSet()` for the value. 

On that front, does it make sense to automatically wrap any arrays in `createSet()` when using `ADD` and `DELETE` update actions? Does that get in the way of any other behavior?

**Comment by ruicosta042** [comment]
great, I'm closing this issue now as it's fixed by the PR. I've created a new issue #11 for your `createSet` suggestion.. if you could add an example of the expected behavior to that issue, it would be of great help

**Comment by mikestopcontinues** [comment]
Thanks again!
